mkdir $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results

cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELEP_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELEP_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELEP_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELEP_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELEP_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELEP_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELEP_SE19_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_SE19_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELEP_SE19_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_SE19_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELEP_SE19_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_SE19_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELEP_ELFR_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_ELFR_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELEP_ELFR_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_ELFR_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELEP_ELFR_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_ELFR_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELFR_results_short/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_results_short__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELFR_results_short/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_results_short__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELFR_results_short/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_results_short__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_SE19_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_SE19_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_SE19_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_SE19_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_SE19_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_SE19_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELFR_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELFR_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/DD_ELFR_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELFR_SE19_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELFR_SE19_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELFR_SE19_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELFR_SE19_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/2_Two_Tasks/ELFR_SE19_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELFR_SE19_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/ELEP_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/ELEP_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELEP_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/ELFR_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELFR_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/ELFR_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/ELFR_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/SE19_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/SE19_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/DD_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/1_Singular_Tasks/DD_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_DD_ELEP_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_DD_ELEP_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_DD_ELEP_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_DD_ELEP_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_DD_ELEP_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_DD_ELEP_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_DD_ELEP_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_DD_ELEP_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_DD_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_DD_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_DD_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_DD_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_DD_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_DD_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_DD_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_DD_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_ELEP_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_ELEP_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_ELEP_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_ELEP_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_ELEP_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_ELEP_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/SE19_ELFR_ELEP_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/SE19_ELFR_ELEP_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/DD_ELFR_ELEP_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/DD_ELFR_ELEP_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/DD_ELFR_ELEP_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/3_Three_Tasks/DD_ELFR_ELEP_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_results__pretraining.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/4_Four_Tasks/DD_ELFR_ELEP_SE19_results/ELFRContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_SE19_results__ELFRContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/4_Four_Tasks/DD_ELFR_ELEP_SE19_results/ELEPContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_SE19_results__ELEPContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/4_Four_Tasks/DD_ELFR_ELEP_SE19_results/DDContext/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_SE19_results__DDContext.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/4_Four_Tasks/DD_ELFR_ELEP_SE19_results/SE19Context/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_SE19_results__SE19Context.json
cp $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/4_Four_Tasks/DD_ELFR_ELEP_SE19_results/pretraining/logs/*/*/metrics.json $1/EmoMTLExperiments/3_BERT_MTL/1_MTL_Tasks/results/DD_ELFR_ELEP_SE19_results__pretraining.json

